wireplumber.settings = {
    default.target = "sink.system"
}

wireplumber.profiles = {
    main = {
        monitor.alsa = enabled
    }
}

wireplumber.rules = [
    {
        matches = [
            { application.name = "discord" }
            { application.name = "Discord" }
        ]
        actions = {
            update-props = {
                target.object = "sink.discord"
            }
        }
    }
    {
        matches = [
            { application.name = "spotify" }
            { application.name = "Spotify" }
        ]
        actions = {
            update-props = {
                target.object = "sink.spotify"
            }
        }
    }
]
