# chezmoi.ci.toml
# This is a NON-TEMPLATED config file specifically for CI bootstrapping.
# Its main purpose is to provide the [data] block for all templates.
# sourceDir and destDir will be provided by CLI arguments in the CI 'chezmoi apply' task.

[data]
name = "Samir Hassen (CI)"
email = "your_ci_email@example.com"
terminal = "alacritty"
editor = "nvim"
terminal_app_name_mac = "Alacritty"    # For macOS 'open -a'
terminal_cmd_linux = "alacritty"       # For Linux exec
browser_app_name_mac = "Brave Browser" # For macOS 'open -a'
browser_cmd_linux = "brave-browser"    # For Linux exec

# encryption = "gpg" # If you use encrypted files and have GPG set up in CI
# pager = "less -R"
