# for CI/CD
name: "Samir Hassen"
email: "fake@email.com"
terminal: "ghostty"
editor: "nvim"
browser: "brave-browser"
terminal_app_name_mac: "Ghostty"
browser_app_name_mac: "Brave Browser"
terminal_cmd_linux: "ghostty"
browser_cmd_linux: "brave-browser"
monitor_left: "DP-2"
monitor_right: "DP-0"
